[tool.black]
target_version = ["py311"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
packages = ["2015", "2016", "2017", "2021", "2022", "cli", "tests"]

[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Julien Chaumont"]

[tool.poetry.dependencies]
python = "^3.10"
appdirs = "^1.4.4"
beautifulsoup4 = "^4.11.1"
click = "^8.1.3"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
mypy = "^0.991"
pytest = "^6.2"
pytest-xdist = "^3.1.0"
types-appdirs = "^1.4.3"
types-beautifulsoup4 = "^4.11.6"
types-click = "^7.1.8"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
