[tool.black]
target_version = ["py312"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
packages = ["2015", "2016", "2017", "2021", "2022", "cli", "tests"]

[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Julien Chaumont"]

[tool.poetry.dependencies]
python = "^3.12"
appdirs = "^1.4.4"
beautifulsoup4 = "^4.12.2"
click = "^8.1.7"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
black = "^23.11.0"
mypy = "^1.7.1"
pytest = "^7.4.3"
pytest-benchmark = "^4.0.0"
pytest-xdist = "^3.5.0"
types-appdirs = "^1.4.3"
types-beautifulsoup4 = "^4.12.0"
types-click = "^7.1.8"
types-requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
