[project]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = [{ name = "Julien Chaumont"}]
requires-python = ">=3.14"

dependencies = [
    "appdirs~=1.4.4",
    "beautifulsoup4~=4.14.2",
    "click~=8.3.0",
    "httpx~=0.28.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest~=9.0.1",
    "pytest-benchmark~=5.2.0",
    "pytest-xdist~=3.8.0",
    "ty~=0.0.80",
]

[tool.ty.rules]
invalid-method-override = "ignore"

[tool.pytest.ini_options]
addopts = "--benchmark-skip"

[tool.ruff.lint]
extend-ignore = ["B019"]
